cmd_/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o := gcc -Wp,-MD,/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/.drs_grp.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include  -I/usr/src/linux-headers-3.13.0-37-generic/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/linux-headers-3.13.0-37-generic/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.13.0-37-generic/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.13.0-37-generic/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=5390 -DRESOURCE_PRE_ALLOC -DCONFIG_STA_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DRALINK_ATE -DCONFIG_RT2880_ATE_CMD_NEW -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DCARRIER_DETECTION_SUPPORT -DSTATS_COUNT_SUPPORT -DLED_CONTROL_SUPPORT -DRTMP_MAC_PCI -DRT30xx -DRT33xx -DRT3090 -DRT3390 -DRT5390 -DRTMP_PCI_SUPPORT -DRTMP_RF_RW_SUPPORT -DRTMP_EFUSE_SUPPORT -DSPECIFIC_BCN_BUF_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT -DRTMP_INTERNAL_TX_ALC -DVCORECAL_SUPPORT -DIQ_CAL_SUPPORT -DNEW_MBSSID_MODE -DRTMP_TEMPERATURE_COMPENSATION -DDFS_SUPPORT -I/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/include  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(drs_grp)"  -D"KBUILD_MODNAME=KBUILD_STR(rt5390sta)" -c -o /home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/.tmp_drs_grp.o /home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.c

source_/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o := /home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.c

deps_/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o := \
    $(wildcard include/config/sta/support.h) \

/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o: $(deps_/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o)

$(deps_/home/sean/Downloads/2011_1007_RT5390_RT5392_Linux_STA_V2.5.0.3_DPO/os/linux/../../common/drs_grp.o):
